behaviors:
  PlayerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2040
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.1
        gamma: 0.995
        network_settings:
          hidden_units: 256
      gail:
        strength: 0.5
        gamma: 0.9
        encoding_size: 128
        demo_path: Demos\Demo5_0.demo
    behavioral_cloning:
      demo_path: Demos\Demo5_0.demo
      steps: 150000
      strength: 0.5
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 30000
